### ISSUE TITLE
Problem with reverb 

### ISSUE THREAD

**Issue by turpaultn** [google-research/sound-separation#8]
Hi there,

There is a problem of alignment in reverberate_and_mix that translate the audio when applying the reverb.
This is a problem about the alignment with the labels.

I'm putting this issue here since multiple people asked to use this work: [https://hal.inria.fr/hal-02891700](https://hal.inria.fr/hal-02891700) and this work should be updated with the reverb fixed.
The best way to update [https://github.com/turpaultn/dcase20_task4](https://github.com/turpaultn/dcase20_task4) is to update sound-separation repo and I pull the last version.

**Comment by haerdogan** [comment]
Hi Nicolas,

The change to fix the reverb is now pushed out. We added two ways to do it by using the output_align parameter.

1. output_align = 'causal' (default) makes a causal convolution which fixes the earlier problem of advancing the sources and causes slight delay due to the RIRs causing some delays.
2. output_align = 'align_sources' would make sure to align sources with dry sources by advancing each source according to the average peak of RIRs for that source (and all mics) so that the sources appear almost fully aligned with their dry version.

Hakan

**Comment by turpaultn** [comment]
Thank you very much !
